### ISSUE TITLE
Modify ontap-technical-reports

### ISSUE THREAD

**Issue by netapp-chrisgeb** [NetAppDocs/ontap-technical-reports#1]
### Page URL

https://docs.netapp.com/us-en/ontap-technical-reports/index.html

### Page title

ONTAP technical reports

### Summary

- Name the sections w/ solutions in mind. For instance: caching solutions using the FlexCache tech, or single name space storage solutions using the FlexGroup tech
- Simplify the names of the tiles, as the section is already called technical reports 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by adamn-ntap** [comment]
@jenatnetapp is currently redesigned the docs.netapp.com home page and working with marketing on crafting some brief descriptors for products. It might be a good idea to learn about that project to see if anything being done there could have bearing on this.
